version: "3.8"
services:
    db:
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=yHbT6i3FUvA
        - POSTGRES_USER=ching
        - POSTGRES_DB=nodexed
